<?php

// +---------------------------------------------------------------------------+
// | This file is part of the Mojavi package.                                  |
// | Copyright (c) 2003, 2004 Sean Kerr.                                       |
// |                                                                           |
// | For the full copyright and license information, please view the LICENSE   |
// | file that was distributed with this source code. You can also view the    |
// | LICENSE file online at http://www.mojavi.org.                             |
// +---------------------------------------------------------------------------+

/**
 * AutoloadConfigHandler允许您指定一个类的列表第一次使用时自动被包括在内。
 * AutoloadConfigHandler allows you to specify a list of classes that will
 * automatically be included for you upon first use.
 *
 * @package    mojavi
 * @subpackage config
 *
 * @author    Sean Kerr (skerr@mojavi.org)
 * @copyright (c) Sean Kerr, {@link http://www.mojavi.org}
 * @since     3.0.0
 * @version   $Id: AutoloadConfigHandler.class.php 319 2004-11-12 21:34:22Z seank $
 */
class AutoloadConfigHandler extends IniConfigHandler{

    // +-----------------------------------------------------------------------+
    // | METHODS (方法)                                                        |
    // +-----------------------------------------------------------------------+

    /**
     * 这个配置处理程序执行。
     * Execute this configuration handler.
     *
     * @param string An absolute filesystem path to a configuration file.
     *
     * @return string Data to be written to a cache file.
     *
     * @throws <b>ConfigurationException</b> If a requested configuration file
     *                                       does not exist or is not readable.
     * @throws <b>ParseException</b> If a requested configuration file is
     *                               improperly formatted.
     *
     * @author Sean Kerr (skerr@mojavi.org)
     * @since  3.0.0
     */
    public function & execute ($config){

        // set our required categories list and initialize our handler(设置所需的类别列表并初始化处理程序)
        $categories = array('required_categories' => array('autoload'));

        $this->initialize($categories);

        // parse the ini(解析ini)
        $ini = $this->parseIni($config);

        // init our data array(数组初始化数据)
        $data = array();

        // let's do our fancy work(让我们做我们喜欢的工作)
        foreach ($ini['autoload'] as $class => &$file){

            $file = $this->replaceConstants($file);
            $file = $this->replacePath($file);

            if (!is_readable($file)){

                // the class path doesn't exist(类路径不存在)
                $error = 'Configuration file "%s" specifies class "%s" with ' .
                         'nonexistent or unreadable file "%s"';
                $error = sprintf($error, $config, $class, $file);

                throw new ParseException($error);

            }

            $tmp    = "\$classes['%s'] = '%s';";
            $data[] = sprintf($tmp, $class, $file);

        }

        // compile data(编制资料)
        $retval = "<?php\n" .
                  "// auth-generated by AutoloadConfigHandler\n" .
                  "// date: %s\n%s\n?>";
        $retval = sprintf($retval, date('m/d/Y H:i:s'), implode("\n", $data));

        return $retval;

    }

}

?>